//This file is autogenerated. See modules.json and autogenerator.py for details

const fetch = require("node-fetch")

/*
    file_archive.js

    MediaWiki API Demos
    Demo of `Filearchive` module: Get a list of all deleted files.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "query",
    list: "filearchive",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
