//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    filearchive.js

    MediaWiki API Demos
    Enumerate 3 deleted files from filearchive table in descending order.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "query",
    falimit: "3",
    list: "filearchive",
    fadir: "descending",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
