//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_filtered_page_revisions.py

    MediaWiki Action API Code Samples
    Demo of `Revisions` module: Get data including content of last 5 revisions of the title [[API:Geosearch]] made after July 1st 2018 excluding changes made by the user SSethi (WMF)

    MIT License
*/

var url = "https://mediawiki.org/w/api.php"; 

var params = {
    action: "query",
    prop: "revisions",
    titles: "API:Geosearch",
    rvlimit: "5",
    rvprop: "timestamp|user|comment|content",
    rvdir: "newer",
    rvstart: "2018-07-01T00:00:00Z",
    rvexcludeuser: "SSethi (WMF)",
    rvslots: "main",
    formatversion: "2",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
