//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_blocked_users.js

    MediaWiki API Demos
    Demo of `Blocks` module: GET request to list recent blocked users.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "query",
    list: "blocks",
    bklimit: "3",
    bkprop: "id|user|by|timestamp|expiry|reason|range|flags",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response.query.blocks);})
    .catch(function(error){console.log(error);});
