//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_alldeletedrevs.js

    MediaWiki API Demos
    Demo of `alldeletedrevisions` module: List the all deleted revisions from User

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "query",
    list: "alldeletedrevisions",
    adruser: "Mahesh",
    adrprop: "ids|user|comment",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
