//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_pageswithprops.js

    MediaWiki API Demos
    Demo of `Pageswithprop` module:  List all pages using a given page property.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "query",
    list: "pageswithprop",
    pwppropname: "displaytitle",
    format: "json",
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {
        var pageswithprop = response.query.pageswithprop;
        for (var p in pageswithprop) {
            console.log(pageswithprop[p].title);
        }
    })
    .catch(function(error){console.log(error);});
