//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_allfileusages.js

    MediaWiki API Demos
    Demo of `allfileusage` module: List all file usages, including non-existing.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "query",
    format: "json",
    list: "allfileusages",
    afprefix: "Icon",
    afprop: "ids|title"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {
        var usages = response.query.allfileusages;
        for (var img in usages) {
            console.log(usages[img].title);
        }
    })
    .catch(function(error){console.log(error);});
