//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_user_contributions_feed.js

    MediaWiki API Demos
    Demo of `Feedcontributions` module: Show contributions of a user as an RSS feed.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "feedcontributions",
    user: "Jimbo Wales",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
