//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    languagesearch.js

    MediaWiki Action API Code Samples
    Demo of `Languagesearch` module: Search for a language in any language

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "languagesearch",
    search: "Gu",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
