//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    paraminfo.js

    MediaWiki Action API Code Samples
    Demo of `Paraminfo` module: Get information about other action API modules and their parameters.

    MIT License
*/

var url = "https://en.wikipedia.org/w/api.php"; 

var params = {
    action: "paraminfo",
    format: "json",
    modules: "parse|query+info|query+blah"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
