//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    tokens.js

    MediaWiki Action API Code Samples
    Demo of `Token` module: Fetch token of type `login`

    MIT License
*/

var url = "https://test.wikipedia.org/w/api.php";

var params = {
    action: "query",
    meta: "tokens",
    type: "login",
    format: "json"
};

//url = url + "?origin=*";
url = url + "?"
Object.keys(params).forEach(function (key) { url += "&" + key + "=" + params[key]; });

fetch(url, {
    method: 'GET', headers: new Headers(
        {
            "Access-Control-Allow-Origin": '*',
            "Content-Type": "application/json",
            "Accept": "application/json",

        }
    ),
})
    .then(function (response) { return response.json(); })
    .then(function (response) { console.log(response); })
    .catch(function (error) { console.log(error); });
