//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    tokens.js

    MediaWiki API Demos
    Demo of `Token` module: Fetch token of type `login`

    MIT License
*/

var url = "https://www.mediawiki.org/w/api.php";

var params = {
    action: "query",
    meta: "tokens",
    type: "login",
    format: "json"
};

url = url + "?origin=*";
Object.keys(params).forEach(function(key){url += "&" + key + "=" + params[key];});

fetch(url)
    .then(function(response){return response.json();})
    .then(function(response) {console.log(response);})
    .catch(function(error){console.log(error);});
