// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	all_messages.js

	MediaWiki API Demos
	Demo of `Allmessages` module: Get the Dutch translations of some messages

	MIT License
*/

var params = {
		action: 'query',
		meta: 'allmessages',
		ammessages: 'august|mainpage|edit|rollback-success',
		amlang: 'nl',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
