// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	compare.js

	MediaWiki API Demos
	Demo of `Compare` module: Compare the current revisions of two different pages.

	MIT License
*/

var params = {
		action: 'compare',
		fromtitle: 'Template:Unsigned',
		totitle: 'Template:UnsignedIP',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
