// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	expand_templates.js

	MediaWiki API Demos
	Demo of `Expandtemplates` module: Obtain general site info.

	MIT License
*/

var params = {
		action: 'expandtemplates',
		text: '{{Project:Sandbox}}',
		prop: 'wikitext',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
