// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	file_repo_info.js

	MediaWiki API Demos
	Demo of `Filerepoinfo` module: Get information about file repositories.

	MIT License
*/

var params = {
		action: 'query',
		meta: 'filerepoinfo',
		friprop: 'url|name|displayname',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
