// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	file_archive.js

	MediaWiki API Demos
	Demo of `Filearchive` module: Get a list of all deleted files.

	MIT License
*/

var params = {
		action: 'query',
		list: 'filearchive',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
