// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_help.js

	MediaWiki API Demos
	Demo of `Help` module: Get help for a specified module.

	MIT License
*/

var params = {
		action: 'help',
		modules: 'query+tokens',
		wrap: '',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
