// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_user_contributions_feed.js

	MediaWiki API Demos
	Demo of `Feedcontributions` module: Show contributions of a user as an RSS feed.

	MIT License
*/

var params = {
		action: 'feedcontributions',
		user: 'Jimbo Wales',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
