// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_info.js

	MediaWiki API Demos
	Demo of `Info` module: Send a GET request to display information about a page.

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		titles: 'Albert Einstein',
		prop: 'info',
		inprop: 'url|talkid'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pages = data.query.pages,
		p;
	for ( p in pages ) {
		console.log( pages[ p ].title + ' has ' + pages[ p ].length + ' bytes.' );
	}
} );
