// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_category_info.js

	MediaWiki API Demos
	Demo of `Categoryinfo` module: Get information about a few categories

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		titles: 'Category:Foo|Category:Infobox templates',
		prop: 'categoryinfo'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pages = data.query.pages,
		page;
	for ( page in pages ) {
		console.log( pages[ page ].title + ' has ' + pages[ page ].categoryinfo.pages + ' pages.' );
	}
} );
