// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_alltransclusions.js

	MediaWiki API Demos
	Demo of `Alltransclusions` module: Get three unique pages
	in the main namespace which contain transclusions.

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'alltransclusions',
		atunique: '1',
		atnamespace: '0',
		atlimit: '3'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var transclusions = data.query.alltransclusions,
		t;
	for ( t in transclusions ) {
		console.log( transclusions[ t ].title );
	}
} );
