// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_protectedtitles.js

	MediaWiki API Demos
	Demo of `Protectedtitles` module: Get the first 2 titles which only sysops can create

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'protectedtitles',
		ptlevel: 'sysop',
		ptlimit: '2'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pages = data.query.protectedtitles,
		p;
	for ( p in pages ) {
		console.log( pages[ p ].title );
	}
} );
