// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_pages_revisions.js

	MediaWiki API Demos
	Demo of `Revisions` module: Get revision data with content for pages with
	titles [[API]] and [[Main Page]]

	MIT License
*/

var params = {
		action: 'query',
		prop: 'revisions',
		titles: 'API|Main Page',
		rvprop: 'timestamp|user|comment|content',
		rvslots: 'main',
		formatversion: '2',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pages = data.query.pages,
		p;
	for ( p in pages ) {
		console.log( pages[ p ].revisions );
	}
} );
