// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_allusers.js

	MediaWiki API Demos
	Demo of `Allusers` module: Get all users, starting from those
	whose name begins with the string, 'Drov'.

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'allusers',
		auprefix: 'Drov'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var users = data.query.allusers,
		u;
	for ( u in users ) {
		console.log( users[ u ].name );
	}
} );
