// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_imageusage.js

	MediaWiki API Demos
	Demo of `Imageusage` module: List the first 3 pages that use a given image title

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'imageusage',
		iutitle: 'File:Wiki_logo_Nupedia.jpg',
		iulimit: '3'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pages = data.query.imageusage,
		p;
	for ( p in pages ) {
		console.log( pages[ p ].title );
	}
} );
