// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_subcategories.js

	MediaWiki API Demos
	Demo of `Categorymembers` module : Get ten subcategories of a category

	MIT License
*/

var params = {
		action: 'query',
		list: 'categorymembers',
		cmtitle: 'Category:Wikipedia',
		cmtype: 'subcat',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var category = data.query.categorymembers,
		cat;
	for ( cat in category ) {
		console.log( category[ cat ].title );
	}
} );
