// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_allrevisions.js

	MediaWiki API Demos
	Demo of `Allrevisions` module: get revision data of multiple pages and users

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'allrevisions',
		arvprop: 'ids|flags|timestamp',
		arvuser: 'Place holder'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var revs = data.query.allrevisions,
		r;
	for ( r in revs ) {
		console.log( revs[ r ] );
	}
} );
