// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_logevents.js

	MediaWiki API Demos
	Demo of `Logevents` module: Get the three most recent logevents.

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'logevents',
		lelimit: '3'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var logs = data.query.logevents,
		l;
	for ( l in logs ) {
		console.log( 'There is ' + logs[ l ].type + ' log for page ' + logs[ l ].title );
	}
} );
