// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_alllinks.js

	MediaWiki API Demos
	Demo of `Alllinks` module: List links pointing to the given namespace.

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'alllinks',
		alnamespace: '0',
		alunique: '1'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var links = data.query.alllinks,
		l;
	for ( l in links ) {
		console.log( links[ l ].title );
	}
} );
