// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_blocked_users.js

	MediaWiki API Demos
	Demo of `Blocks` module: GET request to list recent blocked users.

	MIT License
*/

var params = {
		action: 'query',
		list: 'blocks',
		bklimit: '3',
		bkprop: 'id|user|by|timestamp|expiry|reason|range|flags',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data.query.blocks );
} );
