// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_random.js

	MediaWiki API Demos
	Demo of `Random` module: Get request to list 5 random pages.

	MIT License
*/

var params = {
		action: 'query',
		format: 'json',
		list: 'random',
		rnlimit: '5'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var randoms = data.query.random,
		r;
	for ( r in randoms ) {
		console.log( randoms[ r ].title );
	}
} );
