// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_pageswithprop.js

	MediaWiki API Demos
	Demo of `Pageswithprop` module: List all pages using a given page property.

	MIT License
*/

var params = {
		action: 'query',
		list: 'pageswithprop',
		pwppropname: "displaytitle",
		format: 'json'
	},

api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pageswithprops = data.query.pageswithprop,
		p;
	for ( p in pageswithprops ) {
		console.log( pageswithprops[ p ].title );
	}
} );
