// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_user_watchlist_feed.js

	MediaWiki API Demos
	Demo of `Feedwatchlist` module: Get a watchlist feed from another user.

	MIT License
*/

var params = {
		action: 'feedwatchlist',
		wlowner: 'sample_user',
		wltoken: 'sample_watchlist_token'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
