// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_filtered_page_revisions.js

	MediaWiki API Demos
	Demo of `Revisions` module: Get data including content of last 5 revisions of the
	title [[API:Geosearch]] made after July 1st 2018 excluding changes made by the user SSethi (WMF)

	MIT License
*/

var params = {
		action: 'query',
		prop: 'revisions',
		titles: 'API:Geosearch',
		rvlimit: '5',
		rvprop: 'timestamp|user|comment|content',
		rvdir: 'newer',
		rvstart: '2018-07-01T00:00:00Z',
		rvexcludeuser: 'SSethi (WMF)',
		rvslots: 'main',
		formatversion: '2',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var pages = data.query.pages,
		p;
	for ( p in pages ) {
		console.log( pages[ p ].revisions );
	}
} );
