// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	get_recent_changes.js

	MediaWiki API Demos
	Demo of `RecentChanges` module: Get the three most recent changes with sizes and flags

	MIT License
*/

var params = {
		action: 'query',
		list: 'recentchanges',
		rcprop: 'title|ids|sizes|flags|user',
		rclimit: '3',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	var recentchanges = data.query.recentchanges,
		rc;
	for ( rc in recentchanges ) {
		console.log( recentchanges[ rc ].title );
	}
} );
