// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	langbacklinks.js

	MediaWiki API Demos
	Demo of `Langbacklinks` module: Get pages linking to a given language link

	MIT License
*/

var params = {
		action: 'query',
		list: 'langbacklinks',
		lbltitle: 'Test',
		lbllang: 'fr',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
