// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	langlinks.js

	MediaWiki API Demos
	Demo of `Langlinks` module: Get a list of language links that a given page has

	MIT License
*/

var params = {
		action: 'query',
		titles: 'Albert Einstein',
		prop: 'langlinks',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
