// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	linkshere.js

	MediaWiki API Demos
	Demo of `Linkshere` module: Get a list of pages linking to a given page

	MIT License
*/

var params = {
		action: 'query',
		titles: 'Main Page',
		prop: 'linkshere',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
