// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	opensearch.js

	MediaWiki API Demos
	Demo of `Opensearch` module: Search the wiki and obtain
	results in an OpenSearch (http://www.opensearch.org) format

	MIT License
*/

var params = {
		action: 'opensearch',
		search: 'Hampi',
		limit: '5',
		namespace: '0',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
