// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	pageprops.js

	MediaWiki API Demos
	Demo of `Pageprops` module: Get various properties defined in the page content

	MIT License
*/

var params = {
		action: 'query',
		titles: 'Albert Einstein',
		prop: 'pageprops',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
