// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	parse.js

	MediaWiki API Demos
	Demo of `Parse` module: Parse content of a page

	MIT License
*/

var params = {
		action: 'parse',
		page: 'Pet door',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data.parse.text[ '*' ] );
} );
