// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	rsd.js

	MediaWiki API Demos
	Demo of `Rsd` module: Get request to export an RSD schema.

	MIT License
*/

var params = {
		action: 'rsd',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
