// This file is autogenerated. See modules.json and autogenerator.py for details

/*
	userinfo.js

	MediaWiki API Demos
	Demo of `Userinfo` module: Get general user info and user rights

	MIT License
*/

var params = {
		action: 'query',
		meta: 'userinfo',
		uiprop: 'rights',
		format: 'json'
	},
	api = new mw.Api();

api.get( params ).done( function ( data ) {
	console.log( data );
} );
