//This file is autogenerated

let URL = "https://mediawiki.org/w/api.php"; 

const params = {
    action: "query",
    prop: "revisions",
    titles: "API|Main Page",
    rvprop: "timestamp|user|comment|content",
    rvslots: "main",
    formatversion: "2",
    format: "json"
}

URL = URL + "?origin=*";
Object.keys(params).forEach(key => URL = URL + "&" + key + "=" + params[key]);

fetch(URL)
    .then(response => response.json())
    .then(response => console.log(response))
    .catch(error=>console.log(error))
