//This file is autogenerated

let URL = "https://mediawiki.org/w/api.php"; 

const params = {
    action: "query",
    meta: "tokens",
    type: "login",
    format: "json"
}

URL = URL + "?origin=*";
Object.keys(params).forEach(key => URL = URL + "&" + key + "=" + params[key]);

fetch(URL)
    .then(response => response.json())
    .then(response => console.log(response))
    .catch(error=>console.log(error))
