<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    all_messages.php

    MediaWiki API Demos
    Demo of `Allmessages` module: Get the Dutch translations of some messages

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "meta" => "allmessages",
    "ammessages" => "august|mainpage|edit|rollback-success",
    "amlang" => "nl",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
