<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    compare.php

    MediaWiki API Demos
    Demo of `Compare` module: Compare the current revisions of two different pages.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "compare",
    "fromtitle" => "Template:Unsigned",
    "totitle" => "Template:UnsignedIP",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
