<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_protectedtitles.php

    MediaWiki API Demos
    Demo of `Protectedtitles` module: Get the first 2 titles which only sysops can create

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "format" => "json",
    "list" => "protectedtitles",
    "ptlevel" => "sysop",
    "ptlimit" => "2"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["protectedtitles"] as $k => $v ) {
    echo( $v["title"] . "\n" );
}
