<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_alltransclusions.php

    MediaWiki API Demos
    Demo of `Alltransclusions` module: Get three unique pages in the main namespace which contain transclusions.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "format" => "json",
    "list" => "alltransclusions",
    "atunique" => "1",
    "atnamespace" => "0",
    "atlimit" => "3"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["alltransclusions"] as $k => $v ) {
    echo( $v["title"] . "\n" );
}
