<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_allfileusages.php

    MediaWiki API Demos
    Demo of `allfileusage` module: List all file usages, including non-existing.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "format" => "json",
    "list" => "allfileusages",
    "afprefix" => "Icon",
    "afprop" => "ids|title"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["allfileusages"] as $k => $v ) {
    echo( $v["title"] . "\n" );
}
