<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_user_watchlist_feed.php

    MediaWiki API Demos
    Demo of `Feedwatchlist` module: Get a watchlist feed from another user.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "feedwatchlist",
    "wlowner" => "sample_user",
    "wltoken" => "sample_watchlist_token"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
