<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_allredirects.php

    MediaWiki API Demos
    Demo of `Allredirects` module: Get the first three unique pages containing redirects to the main namespace.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "format" => "json",
    "list" => "allredirects",
    "arunique" => "1",
    "arnamespace" => "0",
    "arlimit" => "3"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["allredirects"] as $k => $v ) {
    echo( $v["title"] . "\n" );
}
