<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_category_info.php

    MediaWiki API Demos
    Demo of `Categoryinfo` module: Get information about a few categories

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "format" => "json",
    "titles" => "Category:Foo|Category:Infobox templates",
    "prop" => "categoryinfo"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["pages"] as $k => $v ) {
    echo( $v["title"] . " has " . $v["categoryinfo"]["pages"] . " pages." . "\n"  );
}