<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_pageswithprop.php

    MediaWiki API Demos
    Demo of `Pageswithprop` module:  List all pages using a given page property.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "list" => "pageswithprop",
    "pwppropname" => "displaytitle",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );
$ch = curl_init($url);

curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );

$output = curl_exec( $ch );

curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["pageswithprop"] as $k => $v ) {
    echo( $v["title"] . "\n" );
}
