<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_filtered_page_revisions.php

    MediaWiki API Demos
    Demo of `Revisions` module: Get data including content of last 5 revisions of the title [[API:Geosearch]] made after July 1st 2018 excluding changes made by the user SSethi (WMF)

    MIT License
*/

$endPoint = "https://www.mediawiki.org/w/api.php";
$params = [
    "action" => "query",
    "prop" => "revisions",
    "titles" => "API:Geosearch",
    "rvlimit" => "5",
    "rvprop" => "timestamp|user|comment|content",
    "rvdir" => "newer",
    "rvstart" => "2018-07-01T00:00:00Z",
    "rvexcludeuser" => "SSethi (WMF)",
    "rvslots" => "main",
    "formatversion" => "2",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["pages"] as $k => $v ) {
    var_dump( $v["revisions"] );
}
