<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_redirects.php

    MediaWiki API Demos
    Demo of `Redirects` module: Get all redirects to the given page(s)

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "titles" => "Jacques Kallis",
    "prop" => "redirects",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["pages"] as $page ) {
    foreach( $page["redirects"] as $k => $v ) {
        echo( $v["title"] . " redirect to " . $page["title"] . "\n");
    }
}
