<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_allrevisions.php

    MediaWiki API Demos
    Demo of `Allrevisions` module: get revision data of multiple pages and users

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "format" => "json",
    "list" => "allrevisions",
    "arvprop" => "ids|flags|timestamp",
    "arvuser" => "Place holder"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["allrevisions"] as $k => $v ) {
    foreach( $v["revisions"] as $k => $v ) {
        var_dump( $v );
    }
}
