<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    get_alldeletedrevs.php

    MediaWiki API Demos
    Demo of `alldeletedrevisions` module: List the all deleted revisions from User

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "list" => "alldeletedrevisions",
    "adruser" => "Mahesh",
    "adrprop" => "ids|user|comment",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
