<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    iwbacklinks.php

    MediaWiki API Demos
    Demo of `Iwbacklinks` module: Get pages linking to wikibooks:Main_Page.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "list" => "iwbacklinks",
    "iwblprefix" => "wikibooks",
    "iwbltitle" => "Main_Page",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

echo( $output );
