<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    langbacklinks.php

    MediaWiki API Demos
    Demo of `Langbacklinks` module: Get pages linking to a given language link

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "list" => "langbacklinks",
    "lbltitle" => "Test",
    "lbllang" => "fr",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
