<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    linkshere.php

    MediaWiki API Demos
    Demo of `Linkshere` module: Get a list of pages linking to a given page

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "titles" => "Main Page",
    "prop" => "linkshere",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
