<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    paraminfo.php

    MediaWiki API Demos
    Demo of `Paraminfo` module: Get information about other action API modules and their parameters.

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "paraminfo",
    "format" => "json",
    "modules" => "parse|query+info|query"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump( $result );
