<?php

//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    prefixsearch.php

    MediaWiki API Demos
    Demo of `Prefixsearch` module: Perform a prefix search for page titles

    MIT License
*/

$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "query",
    "list" => "prefixsearch",
    "pssearch" => "Star Wars",
    "format" => "json"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );

foreach( $result["query"]["prefixsearch"] as $page ) {
    echo( $page["title"] . "\n" );
}
